language: python
python: 3.7
script:
- pip install pip -U
- pip install -r requirements.txt
- python metadataparser.py
- pelican
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: output/
  target_branch: master
  on:
    branch: sources
